<?php
include "fun22L.php";
$v= array(1,2,3,4,5);
$v2= array(5,6,7,8,9,10);
$S=suma($v);
echo $S;
$S=suma($v2);
echo "<b>Vector 2</b> $S";
$M= media($v);
echo $M;
$M=media($v2);
echo "<b>Vector 2</b> $M";
$SP= sumpa($v);
echo $SP;
$SP=sumpa($v2);
echo "<b>Vector 2</b> $SP";
$MP= mediapa($v);
echo $MP;
$MP=mediapa($v2);
echo "<b>Vector 2</b> $MP";
$SM= sumapo($v,"impares");
echo $SM;
$SM= sumapo($v2,"impares");
echo "<b>Vector 2</b> $SM";
$MQ= mayorque($v,4);
echo $MQ;
$MQ= mayorque($v2,4);
echo "<b>Vector 2</b> $MQ";
$MEQ= menorque($v,4);
echo $MEQ;
$MEQ= menorque($v2,4);
echo "<b>Vector 2</b> $MEQ";
$MAX= maximo($v);
echo $MAX;
$MAX= maximo($v2);
echo "<b>Vector 2</b> $MAX";
$MIN= minimo($v);
echo $MIN;
$MIN= minimo($v2);
echo "<b>Vector 2</b> $MIN";
?>